# Generated by Django 4.1.3 on 2022-12-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_skill_2_skill_3_rename_skills_skill_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
