# Generated by Django 4.1.3 on 2022-12-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_experience_title_alter_interest_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill_3',
            name='thumbnail',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
