# Generated by Django 4.1.3 on 2022-12-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_profile_thumbnail_alter_skill_1_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name/Company')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.IntegerField(verbose_name='Mobile Number')),
                ('description', models.TextField(max_length=250, verbose_name='Job Description ( specify skill in need )')),
            ],
        ),
    ]
