# Generated by Django 4.1.3 on 2022-12-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teammate',
        ),
    ]
