# Generated by Django 4.1.4 on 2022-12-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_teammate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactform',
            new_name='contact',
        ),
    ]
